let DASHBOARD_DATA=[];let CHARTS={};
async function loadData(){const r=await fetch("data/dashboard_data.json?v="+Date.now());DASHBOARD_DATA=await r.json();console.log("Loaded records:",DASHBOARD_DATA.length);return DASHBOARD_DATA}
function coreData(){return DASHBOARD_DATA.filter(x=>x&&x.type&&x.model)}
function n(v){return Number(v||0)}function money(v){v=n(v);if(Math.abs(v)>=1e9)return(v/1e9).toFixed(1)+"B";if(Math.abs(v)>=1e6)return(v/1e6).toFixed(1)+"M";if(Math.abs(v)>=1e3)return(v/1e3).toFixed(1)+"K";return v.toLocaleString()}function pct(v){return n(v).toFixed(1)+"%"}
function weekNo(v){const m=String(v||"").match(/\d+/);return m?Number(m[0]):0}function monthName(m){return["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][Number(m)]||m||"-"}function salesmanName(x){return x["Sales Staff"]||x.salesman||x.salesStaff||"Unknown"}function sourceName(x){return x.source||x["Source (ที่มาลูกค้า)"]||x.Source||"Unknown"}function valueOf(x){return n(x.msrp||x.salesValue)}function gpOf(x){return n(x.gp1||x.grossProfit)}function comOf(x){return n(x.commission)}
function unique(a){return[...new Set(a.filter(v=>v!==undefined&&v!==null&&String(v).trim()!==""))]}
function fillFilters(data){fillSelect("yearFilter",unique(data.map(x=>x.year)).sort(),"This Year");fillSelect("monthFilter",unique(data.map(x=>x.month)).sort((a,b)=>n(a)-n(b)),"All Months",monthName);fillSelect("weekFilter",unique(data.map(x=>x.week)).sort((a,b)=>weekNo(a)-weekNo(b)),"All Weeks",v=>"W"+String(weekNo(v)).padStart(2,"0"));fillSelect("dealerFilter",unique(data.map(x=>x.dealer)).sort(),"All Dealers");fillSelect("salesmanFilter",unique(data.map(salesmanName)).sort(),"All Salesmen")}
function fillSelect(id,values,label,fmt){const el=document.getElementById(id);if(!el)return;el.innerHTML=`<option value="">${label}</option>`;values.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=fmt?fmt(v):v;el.appendChild(o)})}
function filteredData(){const y=document.getElementById("yearFilter")?.value||"",m=document.getElementById("monthFilter")?.value||"",w=document.getElementById("weekFilter")?.value||"",d=document.getElementById("dealerFilter")?.value||"",s=document.getElementById("salesmanFilter")?.value||"";return coreData().filter(x=>(!y||String(x.year)===String(y))&&(!m||String(x.month)===String(m))&&(!w||weekNo(x.week)===weekNo(w))&&(!d||String(x.dealer)===d)&&(!s||salesmanName(x)===s))}
function bindFilters(update){["yearFilter","monthFilter","weekFilter","dealerFilter","salesmanFilter"].forEach(id=>document.getElementById(id)?.addEventListener("change",update));document.getElementById("resetFilter")?.addEventListener("click",()=>{["yearFilter","monthFilter","weekFilter","dealerFilter","salesmanFilter"].forEach(id=>{const el=document.getElementById(id);if(el)el.value=""});update()})}
function kpi(data){const units=data.length,sales=data.reduce((s,x)=>s+valueOf(x),0),gp=data.reduce((s,x)=>s+gpOf(x),0),com=data.reduce((s,x)=>s+comOf(x),0);return{units,sales,gp,com,gpPct:sales?gp/sales*100:0,avg:units?sales/units:0}}
function group(data,getter){const map={};data.forEach(x=>{const key=getter(x)||"Unknown";if(!map[key])map[key]={name:key,units:0,sales:0,gp:0,com:0};map[key].units++;map[key].sales+=valueOf(x);map[key].gp+=gpOf(x);map[key].com+=comOf(x)});return Object.values(map).map(r=>({...r,gpPct:r.sales?r.gp/r.sales*100:0,share:data.length?r.units/data.length*100:0})).sort((a,b)=>b.units-a.units)}
function set(id,val){const el=document.getElementById(id);if(el)el.innerHTML=val}
function chart(id,config){const ctx=document.getElementById(id);if(!ctx||typeof Chart==="undefined")return;if(CHARTS[id])CHARTS[id].destroy();CHARTS[id]=new Chart(ctx,config)}
function commonOptions(){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{boxWidth:10,font:{weight:"700"}}}},scales:{x:{grid:{display:false},ticks:{font:{size:11,weight:"700"}}},y:{beginAtZero:true,ticks:{font:{size:11,weight:"700"}}}}}}
function renderKpis(k){set("kpiUnits",k.units.toLocaleString());set("kpiSales",money(k.sales));set("kpiGp",money(k.gp));set("kpiGpPct",pct(k.gpPct));set("kpiCom",money(k.com));set("kpiAvg",money(k.avg))}
function renderRankList(id,rows,valueKey="units"){const t=document.getElementById(id);if(!t)return;const max=rows[0]?.[valueKey]||1;t.innerHTML=rows.slice(0,6).map((r,i)=>`<div class="rank-row"><div class="rank-no">${i+1}</div><div><div class="rank-name">${r.name}</div><div class="rank-meta">${r.units.toLocaleString()} units | GP ${pct(r.gpPct)} | Share ${pct(r.share)}</div><div class="bar"><div class="fill" style="width:${r[valueKey]/max*100}%"></div></div></div><div class="rank-value">${r[valueKey].toLocaleString?.()||r[valueKey]}</div></div>`).join("")}
