let dealerRadarChart=null,dealerStockAgeChart=null;
window.addEventListener('DOMContentLoaded',async()=>{await loadDashboardData();init();});
const $=id=>document.getElementById(id),n=v=>Number(v||0),txt=v=>(v??'').toString().trim();function core(){return typeof getCoreProductData==='function'?getCoreProductData():(window.dashboardData||[]);}function money(v){return typeof formatMoney==='function'?formatMoney(v):(v/1e9).toFixed(1)+'B';}function last(){return typeof getLastRefresh==='function'?getLastRefresh():new Date().toLocaleString();}function weekNo(v){const m=String(v||'').match(/\d+/);return m?+m[0]:0;}function uniq(a){return[...new Set(a.filter(x=>txt(x)))]}function fill(id,vals,label){const el=$(id);if(!el)return;el.innerHTML='<option value="">'+label+'</option>';vals.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o);});}
function init(){const d=core();fill('yearFilter',uniq(d.map(x=>x.year)).sort(),'All years');fill('monthFilter',uniq(d.map(x=>x.month)).sort((a,b)=>a-b),'All months');fill('weekFilter',uniq(d.map(x=>x.week)).sort((a,b)=>weekNo(a)-weekNo(b)),'All weeks');fill('dealerFilter',uniq(d.map(x=>x.dealer)).sort(),'All dealers');fill('typeFilter',uniq(d.map(x=>x.type)).sort(),'All types');['yearFilter','monthFilter','weekFilter','dealerFilter','typeFilter'].forEach(id=>$(id)?.addEventListener('change',update));$('resetFilter')?.addEventListener('click',()=>{['yearFilter','monthFilter','weekFilter','dealerFilter','typeFilter'].forEach(id=>{if($(id))$(id).value=''});update();});update();}
function filtered(){const y=$('yearFilter')?.value||'',m=$('monthFilter')?.value||'',w=$('weekFilter')?.value||'',de=$('dealerFilter')?.value||'',t=$('typeFilter')?.value||'';return core().filter(x=>(!y||String(x.year)===String(y))&&(!m||String(x.month)===String(m))&&(!w||weekNo(x.week)===weekNo(w))&&(!de||x.dealer===de)&&(!t||x.type===t));}
function group(d,getter){const m={};d.forEach(x=>{const k=getter(x)||'Unknown';if(!m[k])m[k]={name:k,units:0,value:0,gp:0};m[k].units++;m[k].value+=n(x.msrp);m[k].gp+=n(x.gp1);});return Object.values(m).map(x=>({...x,gpPct:x.value?x.gp/x.value*100:0})).sort((a,b)=>b.units-a.units);}
function update(){const d=filtered(),dealers=group(d,x=>x.dealer);$('lastRefresh').textContent=last();$('dealerCountTop').textContent=dealers.length;$('bestDealerTop').textContent=dealers[0]?.name||'-';$('kpiDealers').textContent=dealers.length;$('kpiSales').textContent=d.length.toLocaleString();$('kpiGP').textContent=money(d.reduce((s,x)=>s+n(x.gp1),0));renderList('dealerRankingList',dealers);renderRadar(dealers);renderFunnel();renderHealth(dealers);renderStockAge();renderCollections();renderCoverage(dealers);$('aiBestDealer').textContent=dealers[0]?.name||'-';$('aiWarningDealer').textContent=dealers.at(-1)?.name||'-';$('aiStockAction').textContent='Balance Stock';$('aiDealerAction').textContent='Focus Top Dealer';}
function renderList(id,rows){const el=$(id);if(!el)return;const max=rows[0]?.units||1;el.innerHTML=rows.map((r,i)=>`<div class="clean-item"><div class="clean-rank">${i+1}</div><div><div class="clean-name">${r.name}</div><div class="clean-meta">${r.units} units | GP ${r.gpPct.toFixed(1)}% | ${money(r.value)}</div><div class="clean-bar"><div class="clean-fill" style="width:${r.units/max*100}%"></div></div></div><div class="clean-value">${r.units}</div></div>`).join('')||'<p>No data</p>';}
function renderRadar(rows){const c=$('dealerRadarChart');if(!c||typeof Chart==='undefined')return;dealerRadarChart?.destroy();dealerRadarChart=new Chart(c,{type:'radar',data:{labels:['Sales','Stock','Service','Customer','Training'],datasets:rows.slice(0,3).map((r,i)=>({label:r.name,data:[r.units%100,60+i*10,70-i*8,65+i*7,55+i*12],borderColor:['#ff5a00','#12b89d','#9aa3af'][i],backgroundColor:['rgba(255,90,0,.12)','rgba(18,184,157,.12)','rgba(154,163,175,.12)'][i]}))},options:{responsive:true,maintainAspectRatio:false,scales:{r:{beginAtZero:true,max:100}},plugins:{legend:{position:'right'}}}});}
function renderFunnel(){const el=$('dealerFunnel');if(!el)return;el.innerHTML=['Lead|4,852','Quotation|2,986','Booking|1,986','Delivery|2,842'].map(x=>{const[a,b]=x.split('|');return`<div class="funnel-step"><span>${a}</span><strong>${b}</strong></div>`}).join('');}
function renderHealth(rows){const el=$('dealerHealth');if(!el)return;el.innerHTML=rows.slice(0,4).map((r,i)=>`<div class="score-row"><strong>${r.name}</strong><span class="status ${i==0?'good':i==1?'warn':'bad'}">${i==0?'Healthy':i==1?'Warning':'Critical'}</span></div>`).join('');}
function renderCollections(){const el=$('collectionList');if(!el)return;el.innerHTML=`<div class="score-row"><strong>Outstanding</strong><span>22.6M MMK</span></div><div class="score-row"><strong>Overdue</strong><span>3.2M MMK</span></div><div class="score-row"><strong>Collection Rate</strong><span>92.4%</span></div>`;}
function renderCoverage(rows){const el=$('coverageList');if(!el)return;el.innerHTML=rows.slice(0,4).map((r,i)=>`<div class="score-row"><strong>${r.name}</strong><span>${68+i*5}%</span></div>`).join('');}
function renderStockAge(){const c=$('dealerStockAgeChart');if(!c||typeof Chart==='undefined')return;dealerStockAgeChart?.destroy();dealerStockAgeChart=new Chart(c,{type:'doughnut',data:{labels:['0-30','31-60','61-90','90+'],datasets:[{data:[66,54,40,26],backgroundColor:['#9aa3af','#ffb000','#ff7a18','#ff5a00'],borderColor:'#fff',borderWidth:5}]},options:{responsive:true,maintainAspectRatio:false,cutout:'60%'}});}
