let productTrendChart=null,typeMixChart=null,stockAgeChart=null;
window.addEventListener('DOMContentLoaded',async()=>{await loadDashboardData();initProductDashboard();});
const $=id=>document.getElementById(id);const n=v=>Number(v||0);const txt=v=>(v??'').toString().trim();
function core(){return typeof getCoreProductData==='function'?getCoreProductData():(window.dashboardData||[]);}function money(v){return typeof formatMoney==='function'?formatMoney(v):(v/1e9).toFixed(1)+'B';}function last(){return typeof getLastRefresh==='function'?getLastRefresh():new Date().toLocaleString();}
function weekNo(v){const m=String(v||'').match(/\d+/);return m?+m[0]:0;}function uniq(a){return [...new Set(a.filter(x=>txt(x)))];}
function fill(id,vals,label,fmt){const el=$(id);if(!el)return;el.innerHTML='<option value="">'+label+'</option>';vals.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=fmt?fmt(v):v;el.appendChild(o);});}
function initProductDashboard(){populateFilters();['yearFilter','monthFilter','weekFilter','dealerFilter','typeFilter'].forEach(id=>$(id)?.addEventListener('change',update));$('resetFilter')?.addEventListener('click',()=>{['yearFilter','monthFilter','weekFilter','dealerFilter','typeFilter'].forEach(id=>{if($(id))$(id).value='';});update();});update();}
function populateFilters(){const d=core();fill('yearFilter',uniq(d.map(x=>x.year)).sort(),'All years');fill('monthFilter',uniq(d.map(x=>x.month)).sort((a,b)=>a-b),'All months');fill('weekFilter',uniq(d.map(x=>x.week)).sort((a,b)=>weekNo(a)-weekNo(b)),'All weeks');fill('dealerFilter',uniq(d.map(x=>x.dealer)).sort(),'All dealers');fill('typeFilter',uniq(d.map(x=>x.type)).sort(),'All types');}
function filtered(){const y=$('yearFilter')?.value||'',m=$('monthFilter')?.value||'',w=$('weekFilter')?.value||'',de=$('dealerFilter')?.value||'',t=$('typeFilter')?.value||'';return core().filter(x=>(!y||String(x.year)===String(y))&&(!m||String(x.month)===String(m))&&(!w||weekNo(x.week)===weekNo(w))&&(!de||x.dealer===de)&&(!t||x.type===t));}
function group(d,getter){const m={};d.forEach(x=>{const k=getter(x)||'Unknown';if(!m[k])m[k]={name:k,units:0,value:0,gp:0};m[k].units++;m[k].value+=n(x.msrp);m[k].gp+=n(x.gp1);});return Object.values(m).map(x=>({...x,gpPct:x.value?x.gp/x.value*100:0,share:d.length?x.units/d.length*100:0})).sort((a,b)=>b.units-a.units);}
function update(){const d=filtered(),k=calcKPI(d),models=group(d,x=>x.model),types=group(d,x=>x.type);$('recordCount').textContent=d.length.toLocaleString();$('lastRefresh').textContent=last();$('topModelTop').textContent=models[0]?.name||'-';$('kpiUnits').textContent=k.units.toLocaleString();$('kpiValue').textContent=money(k.value);$('kpiGP').textContent=money(k.gp);$('kpiGPMargin').textContent=k.gpPct.toFixed(1)+'%';renderList('topModelList',models.slice(0,5));renderTrend(d);renderTypeMix(types);renderMatrix(models);renderHeatmap(d);renderStockAge();$('aiTopModel').textContent=models[0]?.name||'-';$('aiHighGP').textContent=models.slice().sort((a,b)=>b.gpPct-a.gpPct)[0]?.name||'-';$('aiRisk').textContent=models.slice().sort((a,b)=>a.units-b.units)[0]?.name||'-';$('aiRecommend').textContent=(models[0]?.name||'Top model')+' to key dealers';}
function calcKPI(d){const units=d.length,value=d.reduce((s,x)=>s+n(x.msrp),0),gp=d.reduce((s,x)=>s+n(x.gp1),0);return{units,value,gp,gpPct:value?gp/value*100:0};}
function renderList(id,rows){const el=$(id);if(!el)return;const max=rows[0]?.units||1;el.innerHTML=rows.map((r,i)=>`<div class="clean-item"><div class="clean-rank">${i+1}</div><div><div class="clean-name">${r.name}</div><div class="clean-meta">${r.units.toLocaleString()} units | GP ${r.gpPct.toFixed(1)}% | Share ${r.share.toFixed(1)}%</div><div class="clean-bar"><div class="clean-fill" style="width:${r.units/max*100}%"></div></div></div><div class="clean-value">${r.units}</div></div>`).join('')||'<p>No data</p>';}
function renderTrend(d){const c=$('productTrendChart');if(!c||typeof Chart==='undefined')return;const m={};d.forEach(x=>{const mo=n(x.month);if(!mo)return;m[mo]=(m[mo]||0)+1;});const rows=Object.entries(m).map(([month,units])=>({month:+month,units})).sort((a,b)=>a.month-b.month);productTrendChart?.destroy();productTrendChart=new Chart(c,{type:'line',data:{labels:rows.map(x=>'M'+x.month),datasets:[{label:'Units',data:rows.map(x=>x.units),borderColor:'#ff5a00',backgroundColor:'rgba(255,90,0,.12)',fill:true,tension:.35,borderWidth:3,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}},x:{grid:{display:false}}}}});}
function renderTypeMix(rows){const c=$('typeMixChart');if(!c||typeof Chart==='undefined')return;typeMixChart?.destroy();typeMixChart=new Chart(c,{type:'doughnut',data:{labels:rows.map(x=>x.name),datasets:[{data:rows.map(x=>x.units),backgroundColor:['#ff5a00','#12b89d','#ffb000','#9aa3af','#d6dbe3'],borderColor:'#fff',borderWidth:5,spacing:3,borderRadius:10}]},options:{responsive:true,maintainAspectRatio:false,cutout:'62%',plugins:{legend:{position:'right'}}}});}
function renderStockAge(){const c=$('stockAgeChart');if(!c||typeof Chart==='undefined')return;stockAgeChart?.destroy();stockAgeChart=new Chart(c,{type:'doughnut',data:{labels:['0-30 Days','31-60 Days','61-90 Days','90+ Days'],datasets:[{data:[68,54,38,26],backgroundColor:['#9aa3af','#ffb000','#ff7a18','#ff5a00'],borderColor:'#fff',borderWidth:5}]},options:{responsive:true,maintainAspectRatio:false,cutout:'60%'}});}
function renderMatrix(rows){const el=$('productMatrix');if(!el)return;el.querySelectorAll('.dot').forEach(x=>x.remove());const maxU=Math.max(...rows.map(x=>x.units),1),maxG=Math.max(...rows.map(x=>x.gpPct),1);rows.slice(0,8).forEach(r=>{const d=document.createElement('div');d.className='dot';d.title=r.name;d.style.left=(20+r.units/maxU*70)+'%';d.style.bottom=(20+r.gpPct/maxG*70)+'%';el.appendChild(d);});}
function renderHeatmap(d){const el=$('regionalHeatmap');if(!el)return;const models=group(d,x=>x.model).slice(0,4).map(x=>x.name),dealers=uniq(d.map(x=>x.dealer)).slice(0,3);let html='<div class="heat-row"><div class="heat-cell heat-head">Model</div>'+dealers.map(x=>`<div class="heat-cell heat-head">${x}</div>`).join('')+'<div class="heat-cell heat-head">Total</div></div>';models.forEach(model=>{const vals=dealers.map(de=>d.filter(x=>x.model===model&&x.dealer===de).length);const total=vals.reduce((a,b)=>a+b,0);html+='<div class="heat-row"><div class="heat-cell heat-head">'+model+'</div>'+vals.map(v=>`<div class="heat-cell heat-${Math.min(4,Math.max(1,Math.ceil(v/20)))}">${v}</div>`).join('')+`<div class="heat-cell heat-4">${total}</div></div>`;});el.innerHTML=html;}
