/* KMM Salesman Capability Dashboard */
let charts = {};

const EMPLOYEE_META = {
  "KMM": { tenureMonths: 38, training: 5, activity: 45 },
  "03-Hla Myo": { tenureMonths: 32, training: 4, activity: 38 },
  "02-Bo Bo": { tenureMonths: 4, training: 2, activity: 26 },
  "03-Nandar": { tenureMonths: 15, training: 3, activity: 30 },
  "02-Htun Aung": { tenureMonths: 9, training: 2, activity: 22 },
  "03-Lin Aung": { tenureMonths: 14, training: 3, activity: 28 },
  "03-Sandar Lin Naing": { tenureMonths: 8, training: 2, activity: 18 }
};

window.addEventListener("DOMContentLoaded", async () => {
  await loadDashboardData();
  initDashboard();
});

function initDashboard(){populateFilters();bindEvents();updateDashboard();}
function bindEvents(){["yearFilter","monthFilter","weekFilter","dealerFilter","salesmanFilter"].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener("change",updateDashboard)});const r=document.getElementById("resetFilter");if(r)r.addEventListener("click",()=>{["yearFilter","monthFilter","weekFilter","dealerFilter","salesmanFilter"].forEach(id=>{const el=document.getElementById(id);if(el)el.value=""});updateDashboard();});}
function data(){return typeof getCoreProductData==="function"?getCoreProductData():[];}
function nameOf(x){return x["Sales Staff"]||x.salesStaff||"Unknown";}
function sourceOf(x){return x.source||x["Source (ที่มาลูกค้า)"]||x.Source||"Unknown";}
function val(x){return Number(x.msrp||0);} function gp(x){return Number(x.gp1||0);} function com(x){return Number(x.commission||0);} function weekNo(w){const m=String(w||"").match(/\d+/);return m?Number(m[0]):0;}
function money(n){return typeof formatMoney==="function"?formatMoney(n):compact(n);} function compact(n){n=Number(n||0);if(Math.abs(n)>=1e9)return(n/1e9).toFixed(1)+"B";if(Math.abs(n)>=1e6)return(n/1e6).toFixed(1)+"M";if(Math.abs(n)>=1e3)return(n/1e3).toFixed(1)+"K";return n.toLocaleString();}
function unique(a){return[...new Set(a.filter(v=>v!==undefined&&v!==null&&String(v).trim()!==""))];}
function set(id,v){const el=document.getElementById(id);if(el)el.innerHTML=v;}
function monthName(m){return ["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][Number(m)]||m||"-";}
function meta(name){return EMPLOYEE_META[name]||{tenureMonths:12,training:1,activity:15};}

function populateFilters(){const d=data();fill("yearFilter",unique(d.map(x=>x.year)).sort(),"All");fill("monthFilter",unique(d.map(x=>x.month)).sort((a,b)=>a-b),"All",monthName);fill("weekFilter",unique(d.map(x=>x.week)).sort((a,b)=>weekNo(a)-weekNo(b)),"All",v=>"W"+String(weekNo(v)).padStart(2,"0"));fill("dealerFilter",unique(d.map(x=>x.dealer)).sort(),"All");fill("salesmanFilter",unique(d.map(nameOf)).sort(),"All");}
function fill(id,values,label,fmt){const s=document.getElementById(id);if(!s)return;s.innerHTML=`<option value="">${label}</option>`;values.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=fmt?fmt(v):v;s.appendChild(o);});}
function filtered(){const y=document.getElementById("yearFilter")?.value||"",m=document.getElementById("monthFilter")?.value||"",w=document.getElementById("weekFilter")?.value||"",de=document.getElementById("dealerFilter")?.value||"",sn=document.getElementById("salesmanFilter")?.value||"";return data().filter(x=>(!y||String(x.year)===String(y))&&(!m||String(x.month)===String(m))&&(!w||weekNo(x.week)===weekNo(w))&&(!de||String(x.dealer)===String(de))&&(!sn||nameOf(x)===sn));}

function updateDashboard(){const d=filtered();const people=summaryBySalesman(d);const k=kpi(d,people);renderKpi(k);renderSalesmanBars(people);renderExperience(people);renderTraining(people);renderProductSpec(d);renderCapabilityRadar(k);renderMatrix(people);renderStackedProduct(people,d);renderQuality(k);renderTable(people);renderQuickInsight(people,d,k);}
function kpi(d,people){const units=d.length,sales=d.reduce((s,x)=>s+val(x),0),gross=d.reduce((s,x)=>s+gp(x),0),commission=d.reduce((s,x)=>s+com(x),0);const active=people.length;const avgTraining=active?people.reduce((s,p)=>s+p.training,0)/active:0;const avgTenure=active?people.reduce((s,p)=>s+p.tenureMonths,0)/active/12:0;return{units,sales,gross,commission,gpPct:sales?gross/sales*100:0,active,avgTraining,avgTenure,avgPrice:units?sales/units:0,comUnit:units?commission/units:0};}
function renderKpi(k){set("lastRefresh",typeof getLastRefresh==="function"?getLastRefresh():new Date().toLocaleString());set("kpiUnits",k.units.toLocaleString());set("kpiSales",money(k.sales));set("kpiGP",k.gpPct.toFixed(1)+"%");set("kpiSalesman",k.active);set("kpiActiveNote","Active Salesman");set("kpiTraining",k.avgTraining.toFixed(1));set("kpiTenure",k.avgTenure.toFixed(1));}
function summaryBySalesman(d){const map={};d.forEach(x=>{const n=nameOf(x),m=meta(n);if(!map[n])map[n]={name:n,units:0,sales:0,gross:0,commission:0,tenureMonths:m.tenureMonths,training:m.training,activity:m.activity,products:{}};map[n].units++;map[n].sales+=val(x);map[n].gross+=gp(x);map[n].commission+=com(x);const t=x.type||"Unknown";map[n].products[t]=(map[n].products[t]||0)+1;});return Object.values(map).map(p=>{p.gpPct=p.sales?p.gross/p.sales*100:0;p.capability=score(p);p.topProducts=Object.entries(p.products).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);return p;}).sort((a,b)=>b.units-a.units);}
function score(p){const salesScore=Math.min(30,p.units*1.5),gpScore=Math.min(15,Math.max(0,p.gpPct)),actScore=Math.min(15,p.activity/3),trainScore=Math.min(15,p.training*3),tenureScore=Math.min(15,p.tenureMonths/3),mixScore=Math.min(10,Object.keys(p.products).length*2.5);return Math.round(salesScore+gpScore+actScore+trainScore+tenureScore+mixScore);}

function renderSalesmanBars(rows){const t=document.getElementById("salesmanBarList");if(!t)return;const top=rows.slice(0,10),max=top[0]?.units||1;t.innerHTML=top.map((p,i)=>`<div class="mini-item"><div class="mini-rank">${i+1}</div><div><div class="mini-name">${p.name}</div><div class="mini-bar"><div class="mini-fill" style="width:${p.units/max*100}%"></div></div></div><div class="mini-val">${p.units}</div></div>`).join("");}
function renderQuality(k){const t=document.getElementById("qualityCards");if(!t)return;t.innerHTML=`<div class="quality-mini"><span>GP% เฉลี่ย</span><strong>${k.gpPct.toFixed(1)}%</strong><p>ทั้งทีมที่เลือก</p></div><div class="quality-mini"><span>มูลค่าเฉลี่ย/คัน</span><strong>${money(k.avgPrice)}</strong><p>MMK/Unit</p></div><div class="quality-mini"><span>Commission / Unit</span><strong>${money(k.comUnit)}</strong><p>ประสิทธิภาพค่าคอม</p></div>`;}
function renderTable(rows){const b=document.getElementById("detailTableBody");if(!b)return;b.innerHTML=rows.slice(0,20).map((p,i)=>`<tr><td>${i+1}</td><td>${p.name}</td><td>${tenureText(p.tenureMonths)}</td><td>${p.training}</td><td>${p.units}</td><td>${money(p.sales)}</td><td>${p.gpPct.toFixed(1)}%</td><td>${money(p.commission)}</td><td>${p.activity}</td><td>${p.capability}</td><td>${p.topProducts[0]||"-"}</td><td>${p.topProducts[1]||"-"}</td></tr>`).join("");}
function tenureText(m){if(m>=12)return Math.floor(m/12)+" ปี "+(m%12?m%12+" เดือน":"");return m+" เดือน";}
function renderQuickInsight(rows,d,k){const t=document.getElementById("quickInsight");if(!t)return;const top=rows[0]||{name:"-",units:0};const bestGp=[...rows].sort((a,b)=>b.gpPct-a.gpPct)[0]||{name:"-",gpPct:0};const prod=topItem(d,x=>x.type||"Unknown");t.innerHTML=`<li>Top Salesman<br>${top.name}<br>${top.units} Units</li><li>Highest GP%<br>${bestGp.name}<br>${bestGp.gpPct.toFixed(1)}%</li><li>Top Product<br>${prod.name}<br>${prod.share.toFixed(1)}%</li>`;}
function topItem(d,getter){const rows=breakdown(d,getter);return rows[0]||{name:"-",units:0,share:0};}
function breakdown(d,getter){const m={};d.forEach(x=>{const k=getter(x)||"Unknown";m[k]=(m[k]||0)+1;});return Object.entries(m).map(([name,units])=>({name,units,share:d.length?units/d.length*100:0})).sort((a,b)=>b.units-a.units);}

function destroy(id){if(charts[id]){charts[id].destroy();charts[id]=null;}}
function baseOptions(){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"right",labels:{boxWidth:10,font:{size:11}}}},scales:{x:{ticks:{font:{size:10}},grid:{display:false}},y:{ticks:{font:{size:10}},beginAtZero:true}}};}
function renderExperience(rows){const buckets={"มากกว่า 3 ปี":0,"1 - 3 ปี":0,"6 เดือน - 1 ปี":0,"น้อยกว่า 6 เดือน":0};rows.forEach(p=>{if(p.tenureMonths>36)buckets["มากกว่า 3 ปี"]++;else if(p.tenureMonths>=12)buckets["1 - 3 ปี"]++;else if(p.tenureMonths>=6)buckets["6 เดือน - 1 ปี"]++;else buckets["น้อยกว่า 6 เดือน"]++;});pie("experienceChart",Object.keys(buckets),Object.values(buckets),"doughnut");}
function renderTraining(rows){const buckets={"5+ หลักสูตร":0,"3 - 4 หลักสูตร":0,"1 - 2 หลักสูตร":0,"ยังไม่อบรม":0};rows.forEach(p=>{if(p.training>=5)buckets["5+ หลักสูตร"]++;else if(p.training>=3)buckets["3 - 4 หลักสูตร"]++;else if(p.training>=1)buckets["1 - 2 หลักสูตร"]++;else buckets["ยังไม่อบรม"]++;});bar("trainingChart",Object.keys(buckets),Object.values(buckets),"bar");}
function renderProductSpec(d){const rows=breakdown(d,x=>x.type||"Unknown").slice(0,5);pie("productSpecChart",rows.map(x=>x.name),rows.map(x=>x.units),"doughnut");}
function renderCapabilityRadar(k){destroy("capabilityRadarChart");const c=document.getElementById("capabilityRadarChart");if(!c)return;charts.capabilityRadarChart=new Chart(c,{type:"radar",data:{labels:["ยอดขาย","GP%","อบรม","อายุงาน","กิจกรรม","สินค้า"],datasets:[{label:"Score",data:[Math.min(100,k.units*2),Math.min(100,k.gpPct*8),Math.min(100,k.avgTraining*20),Math.min(100,k.avgTenure*25),70,75],borderColor:"#ff6f00",backgroundColor:"rgba(255,111,0,.12)",pointRadius:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{r:{beginAtZero:true,max:100,ticks:{display:false}}}}});}
function renderMatrix(rows){destroy("matrixChart");const c=document.getElementById("matrixChart");if(!c)return;charts.matrixChart=new Chart(c,{type:"scatter",data:{datasets:[{label:"Salesman",data:rows.map(p=>({x:p.units,y:p.capability,name:p.name})),backgroundColor:"#13b99a"}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:ctx=>`${ctx.raw.name}: ${ctx.raw.x} units / score ${ctx.raw.y}`}}},scales:{x:{title:{display:true,text:"ผลงาน (Units)"},beginAtZero:true},y:{title:{display:true,text:"ศักยภาพ"},beginAtZero:true,max:100}}}});}
function renderStackedProduct(rows,d){const top=rows.slice(0,5);const types=breakdown(d,x=>x.type||"Unknown").slice(0,4).map(x=>x.name);destroy("stackedProductChart");const c=document.getElementById("stackedProductChart");if(!c)return;charts.stackedProductChart=new Chart(c,{type:"bar",data:{labels:top.map(p=>p.name),datasets:types.map(t=>({label:t,data:top.map(p=>p.products[t]||0)}))},options:{indexAxis:"y",responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom",labels:{boxWidth:8,font:{size:10}}}},scales:{x:{stacked:true,beginAtZero:true,ticks:{font:{size:10}}},y:{stacked:true,ticks:{font:{size:10}}}}}});}
function pie(id,labels,values,type){destroy(id);const c=document.getElementById(id);if(!c)return;charts[id]=new Chart(c,{type,data:{labels,datasets:[{data:values,backgroundColor:["#ff6f00","#13b99a","#f5b000","#9ca3af","#2563eb","#dc2626"],borderColor:"#fff",borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,cutout:type==="doughnut"?"58%":0,plugins:{legend:{position:"right",labels:{boxWidth:10,font:{size:11}}}}}});}
function bar(id,labels,values,type){destroy(id);const c=document.getElementById(id);if(!c)return;charts[id]=new Chart(c,{type,data:{labels,datasets:[{data:values,backgroundColor:"#ff6f00",borderRadius:8}]},options:{indexAxis:"y",responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,ticks:{precision:0,font:{size:10}}},y:{ticks:{font:{size:10}}}}}});}
